meta_product_name: "Good Terms"
meta_title: "Good Terms | Because sharing is caring"
meta_description: "Good Terms if the definitive website for keeping track of all your lent and borrowed goods. We make sure you stay on good terms with your friends!"
meta_image: "home-fb.jpg" # should exist in `app/assets/images/`
